name: Coverage Report
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    name: Coveralls Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip;
          pip install --user cpp-coveralls;
          sudo apt update;
      - name: Get HyPhy code
        uses: actions/checkout@v2
      - name: Build HyPhy with profiling flags
        run:
          cmake .;
          make -j HYPHYPROFILE;
      - name: Submit coveralls report
        run:
          coveralls --gcov-options '\-lp';