name: Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  benchmark:
    name: Coveralls Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        - uses: actions/setup-python@v1
        with:
          python-version: 3.7
        run:
          python -m pip install --upgrade pip;
          pip install --user cpp-coveralls
          sudo apt update;
      - name: Build HyPhy with profiling flags
        - uses: actions/checkout@v2
        run:
          cmake .;
          make -j HYPHYPROFILE;
      - name: Submit coveralls report
        run:
          coveralls --gcov-options '\-lp';