name: Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  coverage:
    name: Coveralls Report
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run:
          python -m pip install --upgrade -f .coveralls/requirements.txt;
      - name: Get HyPhy code
        uses: actions/checkout@v2
      - name: Install and activate miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: 'hyphy-test-env'
          environment-file: '.coveralls/env.yml'
          condarc-file: '.coveralls/condarc'
      - name: Build HyPhy
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_token }}
        run:
          cmake .;
          make -j HYPHYDEBUG;
          ln -s HYPHYDEBUG hyphy;
          ln -s HYPHYDEBUG HYPHYMP;
          PATH=.:$PATH make test || true;
      - name: Run tests and generate coverage information
          make test 2>&1 || true; 
          coveralls --gcov-options '\-lp';

